pipeline {
    agent any

    stages {
        stage('build') {
            steps {
                echo 'This is build stage'
                echo 'Added new line for poll SCM'
            }
        }
        stage('test') {
            steps {
                echo 'This is test stage'
            }
        }
    }
}
